# Site settings
title: CTF Writeups

email: jgeralnik@gmail.com
twitter_username: jgeralnik
github_username:  jgeralnik
author: Joey Geralnik

theme: minima
plugins:
  - jekyll-gist
  - jekyll-feed

description: "CTF writeups with magnum, pasten, 0xawes0me"
baseurl: ""

# Build settings
permalink: pretty

google_analytics: UA-51928086-1
