# Site settings
title: Writeups and stuff

authors:
  - email: jgeralnik@gmail.com
    username: jgeralnik
    github: true
    twitter: true

description: "CTF writeups"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3

comments: false
